version: '3.9'
services:
redis:
image: redis:7-alpine
container_name: redis-planetas
ports:
- "6379:6379"
command: ["redis-server", "--appendonly", "yes"]
volumes:
- redisdata:/data
api:
build: .
image: api-planetas-redis:dev
container_name: api-planetas
command: ["npm", "run", "dev"]
ports:
- "3000:3000"
env_file:
- .env
volumes:
- ./:/app
working_dir: /app
depends_on:
- redis
volumes:
redisdata: